inputs:
  #- Stdin:
  #    codec: json
      #codec: json:not_usenumber
  - Kafka:
      decorate_events: false
      topic:
        bngame_player_log_v0_0_1: 1
#        bngame_account_log_v0_0_1: 1
      #assign:
      #   weblog: [0,9]
      codec: json
      consumer_settings:
        bootstrap.servers: "113.125.74.232:9092"
        #bootstrap.servers: "kafka.banagame.com:9092"
        group.id: bana.172.16.0.1191
        max.partition.fetch.bytes: "10485760"
        auto.commit.interval.ms: "5000"
        from.beginning: "true"
        # sasl.mechanism: PLAIN
        # sasl.user: admin
        # sasl.password: admin-secret

filters:
  - Remove:
      fields: ["@timestamp", "@metadata"]
        
  #- Date:
  #    location: Asia/Shanghai
  #    src: crt_time
  #    #target: crt_time
  #    formats:
  #      - "RFC3339"
  #      #- "2006-01-02T15:04:05"
  #      #- "2006-01-02T15:04:05Z07:00"
  #      - "2006-01-02T15:04:05+07:00"
  #      #- "2006-01-02T15:04:05Z0700"
  #      #- "2006-01-02T15:04:05+0700"
  #      - "2006-01-02"
  #      #- "UNIX"
  #      #- "UNIX_MS"
  #    #
outputs:
  #- Stdout: {}
  - Clickhouse:
      #debug: true
      table: "gamelog.player_log"
      log_topic: "bngame_player_log_v0_0_1"
      #conn_max_life_time: 1800
      #username: "default"
      #password: "qE92QEPUxNsGWQ2c"
      hosts:
        - "tcp://127.0.0.1:9000"
      bulk_actions: 2000
      flush_interval: 30
      concurrent: 1
